name: echo_share
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0
  web_socket_channel: ^3.0.2
  flutter_svg: ^2.0.17
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.6
  # flutter_webrtc: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
